steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - |
        gcloud artifacts repositories describe lexileap --location=$_REGION >/dev/null 2>&1 || \
        gcloud artifacts repositories create lexileap --repository-format=docker --location=$_REGION

  # Build container image using Cloud Native Buildpacks (publish directly to Artifact Registry)
  - name: gcr.io/k8s-skaffold/pack
    entrypoint: pack
    args:
      - build
      - australia-southeast1-docker.pkg.dev/$PROJECT_ID/lexileap/lexileap-data:$COMMIT_SHA
      - --builder
      - gcr.io/buildpacks/builder
      - --publish

  # Deploy to Cloud Run with sizing and runtime SA
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE
      - --region=$_REGION
      - --image=australia-southeast1-docker.pkg.dev/$PROJECT_ID/lexileap/lexileap-data:$COMMIT_SHA
      - --no-allow-unauthenticated
      - --memory=$_MEMORY
      - --cpu=$_CPU
      - --concurrency=$_CONCURRENCY
      - --timeout=900s
      - --min-instances=0
      - --max-instances=2
      - --service-account=$_SERVICE_ACCOUNT


  # Ensure scripts bucket exists
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - |
        gsutil ls -b gs://$_SCRIPTS_BUCKET >/dev/null 2>&1 || \
        gsutil mb -l $_REGION gs://$_SCRIPTS_BUCKET

  # Upload startup scripts from repo to GCS
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - |
        gsutil cp scripts/requirements.txt gs://$_SCRIPTS_BUCKET/$_SCRIPTS_PREFIX/requirements.txt
        gsutil cp scripts/ngram_processor.py gs://$_SCRIPTS_BUCKET/$_SCRIPTS_PREFIX/ngram_processor.py
        gsutil cp scripts/compute_engine_startup.sh gs://$_SCRIPTS_BUCKET/$_SCRIPTS_PREFIX/compute_engine_startup.sh


substitutions:
  _SERVICE: lexileap-data
  _REGION: australia-southeast1
  _MEMORY: 2Gi
  _CPU: "2"
  _CONCURRENCY: "20"
  _SERVICE_ACCOUNT: lexileap-cloud-run@business-dfb30.iam.gserviceaccount.com
  _SCRIPTS_BUCKET: $PROJECT_ID-compute-engine-startup
  _SCRIPTS_PREFIX: compute-engine-startup

options:
  logging: CLOUD_LOGGING_ONLY